
Loaded base model.
Loaded base model.
Epoch: [0][0/2069]	Batch Time 13.763 (13.763)	Data Time 0.978 (0.978)	Loss 24.8761 (24.8761)	
Epoch: [0][200/2069]	Batch Time 0.085 (0.155)	Data Time 0.000 (0.005)	Loss 6.0107 (10.5945)	
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 21, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 284, in rebuild_storage_fd
    fd = df.detach()
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/tm_ninnart16/.conda/envs/torch/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "train_n.py", line 303, in <module>
    main()
  File "train_n.py", line 153, in main
    epoch=epoch,
  File "train_n.py", line 201, in train
    losses.update(loss.item(), images.size(0))
KeyboardInterrupt